coords: '../../hivp/savefiles_wqaa/hivp_coords.npy'
resnames: '../../hivp/savefiles_wqaa/hivp_resnames.npy'
icacoffs: '../../hivp/savefiles_wqaa/hivp_icacoffs_60dim.npy'
pname: 'hivp'
saveDir: '../../hivp/savefiles_wqaa/'
figDir: '../../hivp/savefiles_wqaa/figures/'
logfile: '../../hivp/savefiles_wqaa/log.txt'
